export const ADIF_VERSION = "3.1.7";
const MAX_ADIF_BYTES = 16 * 1_024 * 1_024;
const MAX_FIELD_BYTES = 1 * 1_024 * 1_024;
const FIELD_NAME_PATTERN = /^[A-Z][A-Z0-9_]{0,63}$/u;
const TAG_PATTERN = /^([A-Z][A-Z0-9_]{0,63})(?::([0-9]+)(?::([A-Z]))?)?$/u;

const RECORD_FIELD_ORDER = [
  "QSO_DATE",
  "TIME_ON",
  "QSO_DATE_OFF",
  "TIME_OFF",
  "CALL",
  "BAND",
  "FREQ",
  "MODE",
  "SUBMODE",
  "RST_SENT",
  "RST_RCVD",
  "GRIDSQUARE",
  "MY_CALL",
  "STATION_CALLSIGN",
  "MY_GRIDSQUARE",
  "TX_PWR",
  "COMMENT",
  "APP_RADIO_LITE_ID",
  "APP_RADIO_LITE_RADIO_ID",
  "APP_RADIO_LITE_SOURCE",
] as const;

export type AdifFields = Record<string, string>;

export type ParsedAdif = {
  header: AdifFields;
  records: AdifFields[];
  trailingIncomplete: boolean;
};

export class AdifParseError extends Error {}

export function parseAdif(
  input: Uint8Array,
  options: { allowIncompleteTail?: boolean; maxBytes?: number } = {},
): ParsedAdif {
  const bytes = Buffer.isBuffer(input)
    ? input
    : Buffer.from(input.buffer, input.byteOffset, input.byteLength);
  const maxBytes = options.maxBytes ?? MAX_ADIF_BYTES;
  if (!Number.isSafeInteger(maxBytes) || maxBytes < 1 || bytes.length > maxBytes) {
    throw new AdifParseError(`ADIF input exceeds ${maxBytes} bytes`);
  }
  const header: AdifFields = {};
  const records: AdifFields[] = [];
  let current: AdifFields = {};
  let sawHeader = false;
  let sawRecord = false;
  let position = 0;
  let currentStart = 0;

  const incomplete = (message: string): ParsedAdif => {
    if (!options.allowIncompleteTail) {
      throw new AdifParseError(message);
    }
    return { header, records, trailingIncomplete: true };
  };

  while (position < bytes.length) {
    const tagStart = bytes.indexOf(0x3c, position);
    if (tagStart < 0) {
      break;
    }
    const tagEnd = bytes.indexOf(0x3e, tagStart + 1);
    if (tagEnd < 0) {
      return incomplete(`ADIF tag is incomplete at byte ${tagStart}`);
    }
    const rawTag = bytes.subarray(tagStart + 1, tagEnd).toString("ascii").toUpperCase();
    const matched = TAG_PATTERN.exec(rawTag);
    if (matched === null) {
      throw new AdifParseError(`ADIF tag is invalid at byte ${tagStart}`);
    }
    const [, name, lengthText] = matched;
    position = tagEnd + 1;
    if (name === "EOH" || name === "EOR") {
      if (lengthText !== undefined) {
        throw new AdifParseError(`${name} must not declare a data length`);
      }
      if (name === "EOH") {
        if (sawHeader || sawRecord) {
          throw new AdifParseError("ADIF header marker is out of order");
        }
        Object.assign(header, current);
        current = {};
        sawHeader = true;
      } else {
        if (Object.keys(current).length === 0) {
          throw new AdifParseError("ADIF record must contain at least one field");
        }
        records.push(current);
        current = {};
        sawRecord = true;
      }
      currentStart = position;
      continue;
    }
    if (lengthText === undefined) {
      throw new AdifParseError(`ADIF field ${name} is missing its data length`);
    }
    const length = Number(lengthText);
    if (!Number.isSafeInteger(length) || length < 0 || length > MAX_FIELD_BYTES) {
      throw new AdifParseError(`ADIF field ${name} has an invalid data length`);
    }
    if (name in current) {
      throw new AdifParseError(`ADIF record contains duplicate field ${name}`);
    }
    // Wavelog and other deployed loggers emit UTF-8 ADI values and count
    // Unicode characters rather than encoded bytes. ASCII remains identical.
    const field = readUtf8Characters(bytes, position, length, name);
    if (field === null) {
      return incomplete(`ADIF field ${name} is incomplete at byte ${currentStart || tagStart}`);
    }
    if (Object.keys(current).length === 0) {
      currentStart = tagStart;
    }
    current[name] = field.value;
    position = field.nextPosition;
  }

  if (Object.keys(current).length > 0) {
    return incomplete(`ADIF record is incomplete at byte ${currentStart}`);
  }
  return { header, records, trailingIncomplete: false };
}

export function serializeAdif(
  records: readonly AdifFields[],
  header: AdifFields = {},
): Buffer {
  const fields = {
    ADIF_VER: ADIF_VERSION,
    PROGRAMID: "Radio Lite",
    PROGRAMVERSION: "0.1.0",
    ...normalizeFields(header),
  };
  const headerText = [
    "Generated by Radio Lite",
    serializeFields(fields, ["ADIF_VER", "PROGRAMID", "PROGRAMVERSION"]),
    "<EOH>",
  ].join("\r\n");
  return Buffer.concat([
    Buffer.from(`${headerText}\r\n`, "utf8"),
    ...records.map((record) => serializeAdifRecord(record)),
    Buffer.from("\r\n", "ascii"),
  ]);
}

export function serializeAdifRecord(record: AdifFields): Buffer {
  const normalized = normalizeFields(record);
  if (Object.keys(normalized).length === 0) {
    throw new Error("ADIF record must contain at least one field");
  }
  return Buffer.from(`${serializeFields(normalized, RECORD_FIELD_ORDER)}<EOR>\r\n`, "utf8");
}

function serializeFields(fields: AdifFields, preferredOrder: readonly string[]): string {
  const preferred = new Set(preferredOrder);
  const ordered = [
    ...preferredOrder.filter((name) => name in fields),
    ...Object.keys(fields).filter((name) => !preferred.has(name)).sort(),
  ];
  return ordered.map((name) => {
    const value = fields[name];
    return `<${name}:${[...value].length}>${value}`;
  }).join("");
}

function normalizeFields(value: AdifFields): AdifFields {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError("ADIF fields must be an object");
  }
  const normalized: AdifFields = {};
  for (const [rawName, rawValue] of Object.entries(value)) {
    const name = rawName.toUpperCase();
    if (!FIELD_NAME_PATTERN.test(name) || name === "EOH" || name === "EOR") {
      throw new Error(`ADIF field name is invalid: ${rawName}`);
    }
    if (typeof rawValue !== "string") {
      throw new Error(`ADIF field ${name} must be bounded text`);
    }
    const encoded = Buffer.from(rawValue, "utf8");
    if (encoded.length > MAX_FIELD_BYTES || encoded.toString("utf8") !== rawValue) {
      throw new Error(`ADIF field ${name} must use bounded valid UTF-8 text`);
    }
    if (/[\0]/u.test(rawValue)) {
      throw new Error(`ADIF field ${name} contains a prohibited character`);
    }
    if (name in normalized) {
      throw new Error(`ADIF field name is duplicated: ${name}`);
    }
    normalized[name] = rawValue;
  }
  return normalized;
}

function readUtf8Characters(
  bytes: Buffer,
  start: number,
  characterLength: number,
  fieldName: string,
): { value: string; nextPosition: number } | null {
  const presumedAsciiEnd = start + characterLength;
  if (presumedAsciiEnd > bytes.length) {
    return null;
  }
  let ascii = true;
  for (let position = start; position < presumedAsciiEnd; position += 1) {
    if ((bytes[position]! & 0x80) !== 0) {
      ascii = false;
      break;
    }
  }
  if (ascii) {
    return {
      value: bytes.subarray(start, presumedAsciiEnd).toString("ascii"),
      nextPosition: presumedAsciiEnd,
    };
  }

  let nextPosition = start;
  for (let characters = 0; characters < characterLength; characters += 1) {
    if (nextPosition >= bytes.length) {
      return null;
    }
    const width = validUtf8SequenceWidth(bytes, nextPosition);
    if (width === null) {
      throw new AdifParseError(`ADIF field ${fieldName} is not valid UTF-8`);
    }
    if (width === 0) {
      return null;
    }
    nextPosition += width;
    if (nextPosition - start > MAX_FIELD_BYTES) {
      throw new AdifParseError(`ADIF field ${fieldName} has an invalid data length`);
    }
  }
  return {
    value: bytes.subarray(start, nextPosition).toString("utf8"),
    nextPosition,
  };
}

// Returns zero for a truncated sequence and null for malformed UTF-8.
function validUtf8SequenceWidth(bytes: Buffer, position: number): number | null {
  const first = bytes[position]!;
  if (first <= 0x7f) {
    return 1;
  }
  const width = first >= 0xc2 && first <= 0xdf
    ? 2
    : first >= 0xe0 && first <= 0xef
      ? 3
      : first >= 0xf0 && first <= 0xf4
        ? 4
        : null;
  if (width === null) {
    return null;
  }
  if (position + width > bytes.length) {
    return 0;
  }
  const second = bytes[position + 1]!;
  if ((second & 0xc0) !== 0x80) {
    return null;
  }
  if (
    (first === 0xe0 && second < 0xa0) ||
    (first === 0xed && second > 0x9f) ||
    (first === 0xf0 && second < 0x90) ||
    (first === 0xf4 && second > 0x8f)
  ) {
    return null;
  }
  for (let offset = 2; offset < width; offset += 1) {
    if ((bytes[position + offset]! & 0xc0) !== 0x80) {
      return null;
    }
  }
  return width;
}
