export const ADIF_VERSION = "3.1.7";
const MAX_ADIF_BYTES = 16 * 1_024 * 1_024;
const MAX_FIELD_BYTES = 1 * 1_024 * 1_024;
const FIELD_NAME_PATTERN = /^[A-Z][A-Z0-9_]{0,63}$/u;
const TAG_PATTERN = /^([A-Z][A-Z0-9_]{0,63})(?::([0-9]+)(?::([A-Z]))?)?$/u;

const RECORD_FIELD_ORDER = [
  "QSO_DATE",
  "TIME_ON",
  "QSO_DATE_OFF",
  "TIME_OFF",
  "CALL",
  "BAND",
  "FREQ",
  "MODE",
  "SUBMODE",
  "RST_SENT",
  "RST_RCVD",
  "GRIDSQUARE",
  "MY_CALL",
  "STATION_CALLSIGN",
  "MY_GRIDSQUARE",
  "TX_PWR",
  "COMMENT",
  "APP_RADIO_LITE_ID",
  "APP_RADIO_LITE_RADIO_ID",
  "APP_RADIO_LITE_SOURCE",
] as const;

export type AdifFields = Record<string, string>;

export type ParsedAdif = {
  header: AdifFields;
  records: AdifFields[];
  trailingIncomplete: boolean;
};

export class AdifParseError extends Error {}

export function parseAdif(
  input: Uint8Array,
  options: { allowIncompleteTail?: boolean; maxBytes?: number } = {},
): ParsedAdif {
  const bytes = Buffer.isBuffer(input)
    ? input
    : Buffer.from(input.buffer, input.byteOffset, input.byteLength);
  const maxBytes = options.maxBytes ?? MAX_ADIF_BYTES;
  if (!Number.isSafeInteger(maxBytes) || maxBytes < 1 || bytes.length > maxBytes) {
    throw new AdifParseError(`ADIF input exceeds ${maxBytes} bytes`);
  }
  const header: AdifFields = {};
  const records: AdifFields[] = [];
  let current: AdifFields = {};
  let sawHeader = false;
  let sawRecord = false;
  let position = 0;
  let currentStart = 0;

  const incomplete = (message: string): ParsedAdif => {
    if (!options.allowIncompleteTail) {
      throw new AdifParseError(message);
    }
    return { header, records, trailingIncomplete: true };
  };

  while (position < bytes.length) {
    const tagStart = bytes.indexOf(0x3c, position);
    if (tagStart < 0) {
      break;
    }
    const tagEnd = bytes.indexOf(0x3e, tagStart + 1);
    if (tagEnd < 0) {
      return incomplete(`ADIF tag is incomplete at byte ${tagStart}`);
    }
    const rawTag = bytes.subarray(tagStart + 1, tagEnd).toString("ascii").toUpperCase();
    const matched = TAG_PATTERN.exec(rawTag);
    if (matched === null) {
      throw new AdifParseError(`ADIF tag is invalid at byte ${tagStart}`);
    }
    const [, name, lengthText] = matched;
    position = tagEnd + 1;
    if (name === "EOH" || name === "EOR") {
      if (lengthText !== undefined) {
        throw new AdifParseError(`${name} must not declare a data length`);
      }
      if (name === "EOH") {
        if (sawHeader || sawRecord) {
          throw new AdifParseError("ADIF header marker is out of order");
        }
        Object.assign(header, current);
        current = {};
        sawHeader = true;
      } else {
        if (Object.keys(current).length === 0) {
          throw new AdifParseError("ADIF record must contain at least one field");
        }
        records.push(current);
        current = {};
        sawRecord = true;
      }
      currentStart = position;
      continue;
    }
    if (lengthText === undefined) {
      throw new AdifParseError(`ADIF field ${name} is missing its data length`);
    }
    const length = Number(lengthText);
    if (!Number.isSafeInteger(length) || length < 0 || length > MAX_FIELD_BYTES) {
      throw new AdifParseError(`ADIF field ${name} has an invalid data length`);
    }
    if (position + length > bytes.length) {
      return incomplete(`ADIF field ${name} is incomplete at byte ${currentStart || tagStart}`);
    }
    if (name in current) {
      throw new AdifParseError(`ADIF record contains duplicate field ${name}`);
    }
    const valueBytes = bytes.subarray(position, position + length);
    const value = valueBytes.toString("utf8");
    if (!Buffer.from(value, "utf8").equals(valueBytes)) {
      throw new AdifParseError(`ADIF field ${name} is not valid UTF-8`);
    }
    if (Object.keys(current).length === 0) {
      currentStart = tagStart;
    }
    current[name] = value;
    position += length;
  }

  if (Object.keys(current).length > 0) {
    return incomplete(`ADIF record is incomplete at byte ${currentStart}`);
  }
  return { header, records, trailingIncomplete: false };
}

export function serializeAdif(
  records: readonly AdifFields[],
  header: AdifFields = {},
): Buffer {
  const fields = {
    ADIF_VER: ADIF_VERSION,
    PROGRAMID: "Radio Lite",
    PROGRAMVERSION: "0.1.0",
    ...normalizeFields(header),
  };
  const headerText = [
    "Generated by Radio Lite",
    serializeFields(fields, ["ADIF_VER", "PROGRAMID", "PROGRAMVERSION"]),
    "<EOH>",
  ].join("\r\n");
  const recordText = records.map((record) => serializeAdifRecord(record).toString("ascii"));
  return Buffer.from(`${headerText}\r\n${recordText.join("")}\r\n`, "ascii");
}

export function serializeAdifRecord(record: AdifFields): Buffer {
  const normalized = normalizeFields(record);
  if (Object.keys(normalized).length === 0) {
    throw new Error("ADIF record must contain at least one field");
  }
  return Buffer.from(`${serializeFields(normalized, RECORD_FIELD_ORDER)}<EOR>\r\n`, "ascii");
}

function serializeFields(fields: AdifFields, preferredOrder: readonly string[]): string {
  const preferred = new Set(preferredOrder);
  const ordered = [
    ...preferredOrder.filter((name) => name in fields),
    ...Object.keys(fields).filter((name) => !preferred.has(name)).sort(),
  ];
  return ordered.map((name) => {
    const value = fields[name];
    return `<${name}:${value.length}>${value}`;
  }).join("");
}

function normalizeFields(value: AdifFields): AdifFields {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError("ADIF fields must be an object");
  }
  const normalized: AdifFields = {};
  for (const [rawName, rawValue] of Object.entries(value)) {
    const name = rawName.toUpperCase();
    if (!FIELD_NAME_PATTERN.test(name) || name === "EOH" || name === "EOR") {
      throw new Error(`ADIF field name is invalid: ${rawName}`);
    }
    if (typeof rawValue !== "string" || rawValue.length > MAX_FIELD_BYTES) {
      throw new Error(`ADIF field ${name} must be bounded text`);
    }
    if (!/^[\x00-\x7f]*$/u.test(rawValue)) {
      throw new Error(`ADIF field ${name} must use interoperable ASCII text`);
    }
    if (/[\0]/u.test(rawValue)) {
      throw new Error(`ADIF field ${name} contains a prohibited character`);
    }
    if (name in normalized) {
      throw new Error(`ADIF field name is duplicated: ${name}`);
    }
    normalized[name] = rawValue;
  }
  return normalized;
}
